name: Labeler Develop
on:
  pull_request:
    branches:
      - develop

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Add develop label
      - if: github.
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/labeler-develop.yml"
